#ifndef S11N_NET_LIBREADLINECPP_CONFIG_H_INCLUDED
#define S11N_NET_LIBREADLINECPP_CONFIG_H_INCLUDED 1


#define LIBREADLINECPP_USE_LIBEDITLINE 0

#if (1 == LIBREADLINECPP_USE_LIBEDITLINE)
#  define LIBREADLINE_CPP_IMPLEMENTATION_NAME "libeditline"
#  define LIBREADLINECPP_USE_GENUINE_LIBEDIT 0
#else
#  define LIBREADLINECPP_USE_GENUINE_LIBEDIT 0
#endif


#if (1 == LIBREADLINECPP_USE_GENUINE_LIBEDIT)
#  define LIBREADLINE_CPP_IMPLEMENTATION_NAME "libedit"
#  define LIBREADLINECPP_USE_LIBREADLINE 0
#else
#  define LIBREADLINECPP_USE_LIBREADLINE 1
#endif
// ^^^ set to 1 to use libeditline, else 0


#if (1 == LIBREADLINECPP_USE_LIBREADLINE)
#  define LIBREADLINE_CPP_IMPLEMENTATION_NAME "libreadline"
#endif


#ifndef LIBREADLINE_CPP_IMPLEMENTATION_NAME
#  define LIBREADLINE_CPP_IMPLEMENTATION_NAME "stdin"
#endif

#define LIBREADLINECPP_LICENSE "GNU General Public License version 2. Copyright (c) 2002-2005 stephan beal <sgbeal@users.sourceforge.net>."

#define LIBREADLINECPP_VERSION "2005.12.22"


#endif // S11N_NET_LIBREADLINECPP_CONFIG_H_INCLUDED
